### ISSUE TITLE
Error in iOS emulation mode in Chrome

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/polymer-gestures#53]
When emulating any iOS device in Chrome, I get this error:

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    platform-events.js:35(anonymous function)
    platform-events.js:35(anonymous function)
```

Here is the relevant portion of the code:

```
  if (isSafari) {
      // This line throws the exception
      document.body.addEventListener('touchstart', function(){});
  }
```

I'm guessing this is a bug in Chrome rather than Polymer, but I decided to report it here since the issue did not occur in previous polymer versions (e.g. v0.3.2).

**Comment by jenyckee** [comment]
I'm still having the same problem on ipad and chrome ipad emulation
