### ISSUE TITLE
firefox buttons still a problem with tap

### ISSUE THREAD

**Issue by RTFaught** [Polymer/polymer-gestures#77]
I am not getting "tap" events on firefox 33.0.2 on Linux.  I believe I have the latest version of polymer-gestures. I know there was a recent issue about this and that work was done to fix that problem. I traced my problem to line 65 in tap.js.

 tap = (e.buttons ^ 1) && (downState.buttons & 1);

This checks that button 1 is up on the up event. This is not the case and the tap event is blocked. I found this doc online about the buttons:

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.buttons

Gecko notes
Gecko supports the buttons attribute on Windows, Linux (GTK), and Mac with the following restrictions:
...
    On Linux (GTK), the 4th button and the 5th button are not supported. In addition, a mouseup event always has the releasing button information in this attribute value.
...

**Comment by Typel** [comment]
I am experiencing this presently in Firefox v 44.0.2 in Windows 7
on-tap events do not work in Firefox. They do work in Chrome

Using latest elements from bower update
