### ISSUE TITLE
on-up handler called 2 times on browser

### ISSUE THREAD

**Issue by cedric-legallo** [Polymer/polymer-gestures#89]
Hi,
I have a issue (feature ?) with the on-up attribute in the browser, the callback runs 2 times 1 with the mouseup event, and 1 with the polymer CustomEvent. Is this normal ?

Here is my sample element
```javascript
<neon-animated-pages id='pages' touch-action='none'  on-up='upHandler' entry-animation='slide-from-left-animation' exit-animation='slide-right-animation'>
			<template is='dom-repeat' items='{{items}}'>
				<div>something</div>
			</template>
</neon-animated-pages>
```

Context  : 
neon-animation#1.0.1
polymer#1.0.3 (1.0.4 available)
webcomponentsjs#0.7.3 (0.7.5 available)
polymer-gestures#0.5.6

**Comment by azakus** [comment]
Polymer 1.0 and polymer-gestures are incompatible, as a form of polymer-gestures was merged into Polymer in 1.0.
